# RFSoC4x2 Timing Constraints for OpenWiFi
# Clock domain crossings, RFDC interface timing, and MTS constraints

# ===== PRIMARY CLOCKS =====

# External reference clock (if using external source)
# create_clock -period 2.000 -name PL_CLK [get_ports {PL_CLK_p}]

# SYSREF for Multi-Tile Synchronization
# set_input_delay -clock PL_CLK -min 2.000 [get_ports PL_SYSREF_p]
# set_input_delay -clock PL_CLK -max 2.031 [get_ports PL_SYSREF_p]

# ===== CLOCK GROUPS (Asynchronous) =====

# RF Data Converter clocks are auto-generated by IP
# Baseband processing clocks from PS or MMCM
set_clock_groups -asynchronous \
  -group [get_clocks -of_objects [get_pins */rfdc/clk_adc*]] \
  -group [get_clocks -of_objects [get_pins */rfdc/clk_dac*]] \
  -group [get_clocks -of_objects [get_pins zynq_ultra_ps_e_0/inst/pl_clk*]]

# ===== CLOCK DOMAIN CROSSING CONSTRAINTS =====

# False paths through XPM CDC synchronizers (auto-inserted by Vivado)
set_false_path -through [get_pins -hierarchical -filter {NAME =~ *xpm_cdc_single*/syncstages_ff_reg[*]/D}]
set_false_path -through [get_pins -hierarchical -filter {NAME =~ *xpm_cdc_array_single*/syncstages_ff_reg[*]/D}]

# Max delay constraints for data paths crossing clock domains
# RFDC ADC to baseband (if using async clocks)
set_max_delay 5.0 -datapath_only \
  -from [get_clocks -of_objects [get_pins */rfdc/clk_adc*]] \
  -to [get_clocks -of_objects [get_pins zynq_ultra_ps_e_0/inst/pl_clk*]]

# Baseband to RFDC DAC
set_max_delay 5.0 -datapath_only \
  -from [get_clocks -of_objects [get_pins zynq_ultra_ps_e_0/inst/pl_clk*]] \
  -to [get_clocks -of_objects [get_pins */rfdc/clk_dac*]]

# ===== SPECIFIC IP CORE CONSTRAINTS =====

# RX interface CDC paths (adc_intf module)
set_max_delay 5.0 -datapath_only \
  -from [get_pins -hierarchical -filter {NAME =~ *adc_intf*/adc_data_shift_reg[*]/C}] \
  -to [get_pins -hierarchical -filter {NAME =~ *adc_intf*/adc_data_shift_stage1_reg[*]/D}]

# TX interface CDC paths (dac_intf module)
set_max_delay 5.0 -datapath_only \
  -from [get_pins -hierarchical -filter {NAME =~ *dac_intf*/data_from_acc_reg[*]/C}] \
  -to [get_pins -hierarchical -filter {NAME =~ *dac_intf*/data_from_acc_stage1_reg[*]/D}]

# GPIO status CDC
set_max_delay 10.0 -datapath_only \
  -from [get_pins -hierarchical -filter {NAME =~ *gpio_status_rf_reg[*]/C}] \
  -to [get_pins -hierarchical -filter {NAME =~ *gpio_status_bb_reg[*]/D}]

# ===== MULTI-TILE SYNCHRONIZATION (MTS) CONSTRAINTS =====

# SYSREF synchronization max delay
# set_max_delay 1.0 -from [get_ports PL_SYSREF_p]

# MTS clock tree constraints
# set_property CLOCK_DEDICATED_ROUTE ANY_CMT_COLUMN [get_nets -hierarchical *BUFG_PL_CLK*]

# ===== FALSE PATHS =====

# Reset signals (asynchronous)
set_false_path -from [get_ports -filter {NAME =~ *reset*}]
set_false_path -from [get_pins -hierarchical -filter {NAME =~ *rst_reg*/C}]

# Configuration registers to hardware
set_false_path -from [get_pins -hierarchical -filter {NAME =~ *slv_reg*_reg[*]/C}] \
               -to [get_pins -hierarchical -filter {NAME =~ *config_*_reg[*]/D}]

# ===== PHYSICAL CONSTRAINTS =====

# Prevent placement of critical paths across SLR boundaries (if using large device)
# set_property USER_SLR_ASSIGNMENT SLR0 [get_cells -hierarchical -filter {NAME =~ *rx_intf*}]
# set_property USER_SLR_ASSIGNMENT SLR0 [get_cells -hierarchical -filter {NAME =~ *tx_intf*}]

# ===== REPORT CONFIGURATIONS =====

# Generate detailed timing reports
set_property REPORT_STRATEGY {Timing Closure Recommendations} [get_runs impl_1]
