#!/bin/bash
# SPDX-FileCopyrightText: 2025 OpenWiFi Project
# SPDX-License-Identifier: AGPL-3.0-only

#################################################################################
# Enhanced XPU Build Script for antsdr Board (Zynq7020 + AD9361)
#
# Description:
#   Builds the enhanced_xpu IP core with drone Remote ID and monitor mode
#   support for the antsdr SDR platform.
#
# Usage:
#   ./build_antsdr.sh [options]
#
# Options:
#   -c, --clean        Clean previous build
#   -s, --synth-only   Run synthesis only (no implementation)
#   -g, --gui          Open Vivado GUI after build
#   -j, --jobs N       Number of parallel jobs (default: 4)
#   -h, --help         Show this help message
#
# Output:
#   - Synthesis reports in build/synth_reports/
#   - Implementation reports in build/impl_reports/
#   - Bitstream in build/bitstream/ (if implementation completes)
#
# Author: OpenWiFi Team
# Date: 2025-11-22
#################################################################################

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default configuration
CLEAN_BUILD=0
SYNTH_ONLY=0
OPEN_GUI=0
NUM_JOBS=4
BUILD_DIR="build_antsdr"
BOARD_PART="xc7z020clg400-1"
VIVADO_VERSION="2019.1"  # Adjust based on your Vivado version

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IP_DIR="${SCRIPT_DIR}"

#################################################################################
# Helper Functions
#################################################################################

print_header() {
    echo -e "${BLUE}=======================================================================${NC}"
    echo -e "${BLUE} $1 ${NC}"
    echo -e "${BLUE}=======================================================================${NC}"
}

print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_usage() {
    grep '^#' "$0" | grep -E '(Usage|Options|Description):' -A 100 | sed 's/^# //' | sed 's/^#//'
}

check_vivado() {
    if ! command -v vivado &> /dev/null; then
        print_error "Vivado not found in PATH"
        print_info "Please source Vivado settings: source /path/to/Vivado/${VIVADO_VERSION}/settings64.sh"
        exit 1
    fi
    
    VIVADO_VER=$(vivado -version | head -n1 | awk '{print $2}')
    print_info "Found Vivado version: ${VIVADO_VER}"
}

create_build_dir() {
    if [ $CLEAN_BUILD -eq 1 ]; then
        print_info "Cleaning previous build..."
        rm -rf "${IP_DIR}/${BUILD_DIR}"
    fi
    
    mkdir -p "${IP_DIR}/${BUILD_DIR}"
    mkdir -p "${IP_DIR}/${BUILD_DIR}/synth_reports"
    mkdir -p "${IP_DIR}/${BUILD_DIR}/impl_reports"
    mkdir -p "${IP_DIR}/${BUILD_DIR}/bitstream"
    mkdir -p "${IP_DIR}/${BUILD_DIR}/scripts"
}

#################################################################################
# Generate Vivado TCL Script
#################################################################################

generate_tcl_script() {
    print_info "Generating Vivado TCL build script..."
    
    cat > "${IP_DIR}/${BUILD_DIR}/scripts/build_enhanced_xpu.tcl" << 'EOFTCL'
# Enhanced XPU Build Script for antsdr
# Generated by build_antsdr.sh

# Set build configuration
set BOARD_PART "xc7z020clg400-1"
set IP_NAME "enhanced_xpu"
set IP_VERSION "1.0"
set PROJECT_NAME "enhanced_xpu_antsdr"
set BUILD_DIR [file normalize "./build_antsdr"]

# Create project
create_project ${PROJECT_NAME} ${BUILD_DIR}/${PROJECT_NAME} -part ${BOARD_PART} -force

# Set project properties
set_property target_language Verilog [current_project]
set_property simulator_language Mixed [current_project]

# Add source files
set SRC_DIR [file normalize "./src"]

add_files -norecurse ${SRC_DIR}/enhanced_xpu_wrapper.v
add_files -norecurse ${SRC_DIR}/enhanced_pkt_filter.v
add_files -norecurse ${SRC_DIR}/nan_action_handler.v
add_files -norecurse ${SRC_DIR}/remote_id_codec.v
add_files -norecurse ${SRC_DIR}/vendor_ie_codec.v
add_files -norecurse ${SRC_DIR}/frame_injection_ctrl.v

# Add XPU dependency (if available in ip_repo)
set XPU_IP_DIR [file normalize "../../xpu"]
if {[file exists ${XPU_IP_DIR}/src/xpu.v]} {
    add_files -norecurse ${XPU_IP_DIR}/src/xpu.v
    add_files -norecurse ${XPU_IP_DIR}/src/xpu_s_axi.v
    add_files -norecurse ${XPU_IP_DIR}/src/tx_control.v
    add_files -norecurse ${XPU_IP_DIR}/src/pkt_filter_ctl.v
    add_files -norecurse ${XPU_IP_DIR}/src/phy_rx_parse.v
    add_files -norecurse ${XPU_IP_DIR}/src/rssi.v
    add_files -norecurse ${XPU_IP_DIR}/src/cca.v
    add_files -norecurse ${XPU_IP_DIR}/src/csma_ca.v
    add_files -norecurse ${XPU_IP_DIR}/src/cw_exp.v
    add_files -norecurse ${XPU_IP_DIR}/src/tx_on_detection.v
    add_files -norecurse ${XPU_IP_DIR}/src/time_slice_gen.v
    add_files -norecurse ${XPU_IP_DIR}/src/tsf_timer.v
    add_files -norecurse ${XPU_IP_DIR}/src/spi_module.v
    add_files -norecurse ${XPU_IP_DIR}/src/edge_to_flip.v
    puts "INFO: Added base XPU source files"
} else {
    puts "WARNING: Base XPU sources not found at ${XPU_IP_DIR}"
    puts "         You may need to build with IP repository instead"
}

# Update compile order
update_compile_order -fileset sources_1

# Set top module
set_property top enhanced_xpu_wrapper [current_fileset]

puts "INFO: Project setup complete"

# Create synthesis run
if {[get_runs -quiet synth_1] == ""} {
    create_run -name synth_1 -part ${BOARD_PART} -flow {Vivado Synthesis 2019} \
        -strategy "Flow_PerfOptimized_high" -constrset constrs_1
}

set_property strategy "Flow_PerfOptimized_high" [get_runs synth_1]
set_property {steps.synth_design.args.directive} {PerformanceOptimized} [get_runs synth_1]
set_property {steps.synth_design.args.retiming} {1} [get_runs synth_1]
set_property {steps.synth_design.args.fsm_extraction} {one_hot} [get_runs synth_1]

puts "INFO: Starting synthesis..."
reset_run synth_1
launch_runs synth_1 -jobs 4
wait_on_run synth_1

if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    puts "ERROR: Synthesis failed"
    exit 1
}

puts "INFO: Synthesis complete"

# Open synthesized design and generate reports
open_run synth_1 -name synth_1
report_utilization -file ${BUILD_DIR}/synth_reports/utilization_synth.rpt
report_timing_summary -file ${BUILD_DIR}/synth_reports/timing_synth.rpt
report_power -file ${BUILD_DIR}/synth_reports/power_synth.rpt

# Check if we should stop at synthesis
if {[info exists env(SYNTH_ONLY)] && $env(SYNTH_ONLY) == "1"} {
    puts "INFO: Synthesis-only mode, stopping before implementation"
    exit 0
}

# Create implementation run
if {[get_runs -quiet impl_1] == ""} {
    create_run -name impl_1 -part ${BOARD_PART} -flow {Vivado Implementation 2019} \
        -strategy "Performance_ExplorePostRoutePhysOpt" -constrset constrs_1 -parent_run synth_1
}

set_property strategy "Performance_ExplorePostRoutePhysOpt" [get_runs impl_1]
set_property {steps.opt_design.args.directive} {Explore} [get_runs impl_1]
set_property {steps.place_design.args.directive} {Explore} [get_runs impl_1]
set_property {steps.phys_opt_design.args.directive} {Explore} [get_runs impl_1]
set_property {steps.route_design.args.directive} {Explore} [get_runs impl_1]
set_property {steps.post_route_phys_opt_design.is_enabled} {1} [get_runs impl_1]
set_property {steps.post_route_phys_opt_design.args.directive} {Explore} [get_runs impl_1]

puts "INFO: Starting implementation..."
reset_run impl_1
launch_runs impl_1 -jobs 4
wait_on_run impl_1

if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    puts "ERROR: Implementation failed"
    exit 1
}

puts "INFO: Implementation complete"

# Open implemented design and generate reports
open_run impl_1
report_utilization -file ${BUILD_DIR}/impl_reports/utilization_impl.rpt
report_timing_summary -file ${BUILD_DIR}/impl_reports/timing_impl.rpt
report_power -file ${BUILD_DIR}/impl_reports/power_impl.rpt
report_drc -file ${BUILD_DIR}/impl_reports/drc.rpt
report_methodology -file ${BUILD_DIR}/impl_reports/methodology.rpt
report_route_status -file ${BUILD_DIR}/impl_reports/route_status.rpt

# Check timing
set WNS [get_property SLACK [get_timing_paths -max_paths 1 -nworst 1 -setup]]
puts "INFO: Worst Negative Slack (WNS): ${WNS} ns"

if {${WNS} < 0} {
    puts "WARNING: Timing not met! WNS = ${WNS} ns"
    puts "         Consider relaxing constraints or optimizing critical paths"
}

# Generate bitstream
puts "INFO: Generating bitstream..."
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

# Copy bitstream to output directory
file copy -force ${BUILD_DIR}/${PROJECT_NAME}/${PROJECT_NAME}.runs/impl_1/enhanced_xpu_wrapper.bit \
    ${BUILD_DIR}/bitstream/enhanced_xpu_antsdr.bit

puts "INFO: Bitstream generated: ${BUILD_DIR}/bitstream/enhanced_xpu_antsdr.bit"

# Generate timing and utilization summary
puts "\n========================================================================="
puts " BUILD SUMMARY"
puts "========================================================================="
puts "Synthesis:"
puts "  - Reports: ${BUILD_DIR}/synth_reports/"
puts "Implementation:"
puts "  - Reports: ${BUILD_DIR}/impl_reports/"
puts "  - WNS: ${WNS} ns"
puts "Bitstream:"
puts "  - File: ${BUILD_DIR}/bitstream/enhanced_xpu_antsdr.bit"
puts "========================================================================="

# Keep Vivado open if requested
if {[info exists env(OPEN_GUI)] && $env(OPEN_GUI) == "1"} {
    puts "INFO: Keeping Vivado GUI open..."
    start_gui
} else {
    exit 0
}
EOFTCL
}

#################################################################################
# Main Build Flow
#################################################################################

main() {
    print_header "Enhanced XPU Build for antsdr (Zynq7020)"
    
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -c|--clean)
                CLEAN_BUILD=1
                shift
                ;;
            -s|--synth-only)
                SYNTH_ONLY=1
                shift
                ;;
            -g|--gui)
                OPEN_GUI=1
                shift
                ;;
            -j|--jobs)
                NUM_JOBS="$2"
                shift 2
                ;;
            -h|--help)
                print_usage
                exit 0
                ;;
            *)
                print_error "Unknown option: $1"
                print_usage
                exit 1
                ;;
        esac
    done
    
    # Check Vivado installation
    check_vivado
    
    # Create build directories
    create_build_dir
    
    # Generate TCL script
    generate_tcl_script
    
    # Set environment variables for TCL script
    export SYNTH_ONLY
    export OPEN_GUI
    
    # Run Vivado
    print_header "Running Vivado Build"
    print_info "Build directory: ${IP_DIR}/${BUILD_DIR}"
    print_info "Target device: ${BOARD_PART}"
    print_info "Synthesis only: ${SYNTH_ONLY}"
    print_info "Parallel jobs: ${NUM_JOBS}"
    
    cd "${IP_DIR}"
    
    if [ $OPEN_GUI -eq 1 ]; then
        print_info "Opening Vivado GUI..."
        vivado -mode gui -source "${BUILD_DIR}/scripts/build_enhanced_xpu.tcl"
    else
        print_info "Running Vivado in batch mode..."
        vivado -mode batch -source "${BUILD_DIR}/scripts/build_enhanced_xpu.tcl" -log "${BUILD_DIR}/vivado_build.log" -journal "${BUILD_DIR}/vivado_build.jou"
    fi
    
    BUILD_STATUS=$?
    
    if [ $BUILD_STATUS -eq 0 ]; then
        print_header "Build Complete"
        print_info "Synthesis reports: ${IP_DIR}/${BUILD_DIR}/synth_reports/"
        
        if [ $SYNTH_ONLY -eq 0 ]; then
            print_info "Implementation reports: ${IP_DIR}/${BUILD_DIR}/impl_reports/"
            print_info "Bitstream: ${IP_DIR}/${BUILD_DIR}/bitstream/enhanced_xpu_antsdr.bit"
            
            # Check if bitstream was generated
            if [ -f "${IP_DIR}/${BUILD_DIR}/bitstream/enhanced_xpu_antsdr.bit" ]; then
                BITSTREAM_SIZE=$(du -h "${IP_DIR}/${BUILD_DIR}/bitstream/enhanced_xpu_antsdr.bit" | cut -f1)
                print_info "Bitstream size: ${BITSTREAM_SIZE}"
            else
                print_warning "Bitstream not found (build may have failed)"
            fi
        fi
        
        print_info "Vivado log: ${IP_DIR}/${BUILD_DIR}/vivado_build.log"
        print_info "Build successful!"
    else
        print_error "Build failed with status: ${BUILD_STATUS}"
        print_info "Check log file: ${IP_DIR}/${BUILD_DIR}/vivado_build.log"
        exit 1
    fi
}

# Run main function
main "$@"
